package ru.plumsoftware.pdf_doc_files.presentation.theme

import androidx.compose.ui.graphics.Color

val extendedGreen1Light = Color(0xFF005D2E)
val onExtendedGreen1Light = Color(0xFFFFFFFF)
val extendedGreen1ContainerLight = Color(0xFF008645)
val onExtendedGreen1ContainerLight = Color(0xFFFFFFFF)
val extendedBlue1Light = Color(0xFF002AC5)
val onExtendedBlue1Light = Color(0xFFFFFFFF)
val extendedBlue1ContainerLight = Color(0xFF3151FD)
val onExtendedBlue1ContainerLight = Color(0xFFFFFFFF)

val extendedGreen1LightMediumContrast = Color(0xFF004E25)
val onExtendedGreen1LightMediumContrast = Color(0xFFFFFFFF)
val extendedGreen1ContainerLightMediumContrast = Color(0xFF008645)
val onExtendedGreen1ContainerLightMediumContrast = Color(0xFFFFFFFF)
val extendedBlue1LightMediumContrast = Color(0xFF002AC3)
val onExtendedBlue1LightMediumContrast = Color(0xFFFFFFFF)
val extendedBlue1ContainerLightMediumContrast = Color(0xFF3151FD)
val onExtendedBlue1ContainerLightMediumContrast = Color(0xFFFFFFFF)

val extendedGreen1LightHighContrast = Color(0xFF002911)
val onExtendedGreen1LightHighContrast = Color(0xFFFFFFFF)
val extendedGreen1ContainerLightHighContrast = Color(0xFF004E25)
val onExtendedGreen1ContainerLightHighContrast = Color(0xFFFFFFFF)
val extendedBlue1LightHighContrast = Color(0xFF00136E)
val onExtendedBlue1LightHighContrast = Color(0xFFFFFFFF)
val extendedBlue1ContainerLightHighContrast = Color(0xFF002AC3)
val onExtendedBlue1ContainerLightHighContrast = Color(0xFFFFFFFF)

val extendedGreen1Dark = Color(0xFF60DE8A)
val onExtendedGreen1Dark = Color(0xFF00391A)
val extendedGreen1ContainerDark = Color(0xFF008645)
val onExtendedGreen1ContainerDark = Color(0xFFFFFFFF)
val extendedBlue1Dark = Color(0xFFBBC3FF)
val onExtendedBlue1Dark = Color(0xFF001D93)
val extendedBlue1ContainerDark = Color(0xFF2346F4)
val onExtendedBlue1ContainerDark = Color(0xFFFFFFFF)

val extendedGreen1DarkMediumContrast = Color(0xFF65E38E)
val onExtendedGreen1DarkMediumContrast = Color(0xFF001B09)
val extendedGreen1ContainerDarkMediumContrast = Color(0xFF17A659)
val onExtendedGreen1ContainerDarkMediumContrast = Color(0xFF000000)
val extendedBlue1DarkMediumContrast = Color(0xFFC0C7FF)
val onExtendedBlue1DarkMediumContrast = Color(0xFF000B50)
val extendedBlue1ContainerDarkMediumContrast = Color(0xFF7387FF)
val onExtendedBlue1ContainerDarkMediumContrast = Color(0xFF000000)

val extendedGreen1DarkHighContrast = Color(0xFFEFFFEE)
val onExtendedGreen1DarkHighContrast = Color(0xFF000000)
val extendedGreen1ContainerDarkHighContrast = Color(0xFF65E38E)
val onExtendedGreen1ContainerDarkHighContrast = Color(0xFF000000)
val extendedBlue1DarkHighContrast = Color(0xFFFDFAFF)
val onExtendedBlue1DarkHighContrast = Color(0xFF000000)
val extendedBlue1ContainerDarkHighContrast = Color(0xFFC0C7FF)
val onExtendedBlue1ContainerDarkHighContrast = Color(0xFF000000)

