name: build

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build gradle project
        run: ./gradlew app:build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsTemplate.apk
          path: app/build/outputs/apk/debug/app-debug.apk